version: '3'

services:
  db:
    image: mysql:8.2
    restart: always
    env_file:
      - docker/.env
    ports:
      - "3307:3306"

  backend:
    restart: unless-stopped
    env_file:
      - ./development.env
      - docker/.env
    build:
      context: ./server
    entrypoint: /server/dev-entrypoint.sh
    container_name: server
    volumes:
      - ./server:/server
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  frontend:
    env_file:
      - ./development.env
    build:
      context: ./app
    command: sh -c "npm rebuild esbuild && npm run dev"
    container_name: app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    stdin_open: true
    depends_on:
      - backend
