// Icons sourced from https://fonts.google.com/icons using: weight 400, grade 0, optical size 24px, mix of filled and unfilled
import BarChartSVG from './bar_chart.svg?react';
import ChartSVG from './chart.svg?react';
import DarkModeSVG from './dark_mode.svg?react';
import LightModeSVG from './light_mode.svg?react';
import DatasetSVG from './dataset.svg?react';
import GroupSVG from './group.svg?react';
import HubSVG from './hub.svg?react';
import LinkSVG from './link.svg?react';
import PauseSVG from './pause.svg?react';
import PersonSVG from './person.svg?react';
import SearchSVG from './search.svg?react';
import TimelineSVG from './timeline.svg?react';
import AddSVG from './add.svg?react';
import CancelSVG from './cancel.svg?react';
import RecenterSVG from './recenter.svg?react';
import MinusSVG from './minus.svg?react';
import ZoomInSVG from './zoom_in.svg?react';
import ZoomOutSVG from './zoom_out.svg?react';
import AgwagramIconSVG from './agwagram_icon.svg?react';
import { withVectorIcon } from '@imacdonald/phantom';

export const AgwagramIcon = withVectorIcon(AgwagramIconSVG);
export const Add = withVectorIcon(AddSVG);
export const Cancel = withVectorIcon(CancelSVG);
export const Recenter = withVectorIcon(RecenterSVG);
export const Minus = withVectorIcon(MinusSVG);
export const ZoomIn = withVectorIcon(ZoomInSVG);
export const ZoomOut = withVectorIcon(ZoomOutSVG);
export const BarChart = withVectorIcon(BarChartSVG);
export const Chart = withVectorIcon(ChartSVG);
export const DarkMode = withVectorIcon(DarkModeSVG);
export const LightMode = withVectorIcon(LightModeSVG);
export const Dataset = withVectorIcon(DatasetSVG);
export const Group = withVectorIcon(GroupSVG);
export const Hub = withVectorIcon(HubSVG);
export const Link = withVectorIcon(LinkSVG);
export const Pause = withVectorIcon(PauseSVG);
export const Person = withVectorIcon(PersonSVG);
export const Search = withVectorIcon(SearchSVG);
export const Timeline = withVectorIcon(TimelineSVG);
